# Generated by Django 3.0.8 on 2020-07-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('year', models.IntegerField()),
                ('screen_size', models.IntegerField()),
                ('hard_drive_size', models.CharField(max_length=20)),
                ('ram_size', models.CharField(max_length=20)),
                ('processor_speed', models.CharField(max_length=20)),
                ('delivery_option', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('instock', models.BooleanField()),
                ('stock_size', models.IntegerField()),
            ],
        ),
    ]
