# Generated by Django 3.0.8 on 2020-07-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='name',
            field=models.CharField(default='Apple Macbook', max_length=20),
        ),
    ]
